version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /icon-microphone.png
    destination: /webapps/myApp
  - source: /backpacks.png
    destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
